name: my-hello-world-workflow
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: | 
            echo "This is line one for hello world"
            echo "This is line two for hello world"

