name: my-hello-world-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: | 
            echo "This is line one for hello world"
            echo "This is line two for hello world"
            echo "Hello, ${{ vars.MY_NAME }}"

